CREATE TABLE AVIAO (
  ID_AVIAO	 	INT4 NOT NULL,
	NOME_AVIAO	VARCHAR(100) NOT NULL,
	MODELO			VARCHAR(100) NOT NULL,

  PRIMARY KEY (ID_AVIAO)
);

CREATE INDEX IX_AVIAO_01 ON AVIAO(ID_AVIAO, NOME_AVIAO, MODELO);
CREATE SEQUENCE SEQ_AVIAO INCREMENT BY 1 START WITH 1;

CREATE TABLE ASSENTOS (
  ID_ASSENTO	 				INT4 NOT NULL,
	ID_AVIAO						INT4 NOT NULL,
	ASENTO 							VARCHAR(20) NOT NULL,

  PRIMARY KEY (ID_ASSENTO),
	FOREIGN KEY(ID_AVIAO) REFERENCES AVIAO(ID_AVIAO)
);

CREATE SEQUENCE SEQ_ASSENTOS INCREMENT BY 1 START WITH 1;


CREATE TABLE VOO (
	ID_VOO 			INT4 NOT NULL,
	ID_AVIAO		INT4 NOT NULL,
	ORIGEM			VARCHAR(100) NOT NULL,
	DESTINO			VARCHAR(100) NOT NULL,
	DATA_VOO		DATE NOT NULL,
	HORA_VOO		TIME NOT NULL,

	PRIMARY KEY(ID_VOO),
	FOREIGN KEY(ID_AVIAO) REFERENCES AVIAO(ID_AVIAO)
);

CREATE INDEX IX_VOO_01 ON VOO(ID_VOO, ORIGEM, DESTINO, DATA_VOO, HORA_VOO);
CREATE SEQUENCE SEQ_VOO INCREMENT BY 1 START WITH 1;

CREATE TABLE PASSAGEIRO (
	ID_PASSAGEIRO           INT4 NOT NULL,
	ID_VOO        					INT4 NOT NULL,
	ID_ASSENTO      				INT4 NOT NULL,
	NOME          					VARCHAR(200) NOT NULL,
	IND_BAGAGEM 						BOOL NOT NULL,
	CLASSE 									INT4 NOT NULL,

	PRIMARY KEY(ID_PASSAGEIRO),
	FOREIGN KEY(ID_VOO) REFERENCES VOO(ID_VOO),
	FOREIGN KEY(ID_ASSENTO) REFERENCES ASSENTOS(ID_ASSENTO)
);

ALTER TABLE PASSAGEIRO ADD CONSTRAINT UK_PASSAGEIRO_01 UNIQUE (NOME, ID_VOO, ID_ASSENTO);
ALTER TABLE PASSAGEIRO ADD CONSTRAINT CN_PASSAGEIRO_01 CHECK (CLASSE IN (1, 2, 3));
CREATE INDEX IX_PASSAGEIRO_01 ON PASSAGEIRO(ID_PASSAGEIRO, ID_VOO);
CREATE SEQUENCE SEQ_PASSAGEIRO INCREMENT BY 1 START WITH 1;


-- INSERT AVIAO
INSERT INTO AVIAO (ID_AVIAO, NOME_AVIAO, MODELO) VALUES (NEXTVAL('SEQ_AVIAO'), 'GOL', 'GOL 737');
INSERT INTO AVIAO (ID_AVIAO, NOME_AVIAO, MODELO) VALUES (NEXTVAL('SEQ_AVIAO'), 'AZUL', 'AZUL 737');
INSERT INTO AVIAO (ID_AVIAO, NOME_AVIAO, MODELO) VALUES (NEXTVAL('SEQ_AVIAO'), 'TAM', 'TAM 737');

-- INSERT ASSENTOS
INSERT INTO ASSENTOS (ID_ASSENTO, ID_AVIAO, ASENTO) VALUES (NEXTVAL('SEQ_ASSENTOS'), 1, 'A1');
INSERT INTO ASSENTOS (ID_ASSENTO, ID_AVIAO, ASENTO) VALUES (NEXTVAL('SEQ_ASSENTOS'), 1, 'A2');
INSERT INTO ASSENTOS (ID_ASSENTO, ID_AVIAO, ASENTO) VALUES (NEXTVAL('SEQ_ASSENTOS'), 1, 'B1');
INSERT INTO ASSENTOS (ID_ASSENTO, ID_AVIAO, ASENTO) VALUES (NEXTVAL('SEQ_ASSENTOS'), 1, 'B2');
INSERT INTO ASSENTOS (ID_ASSENTO, ID_AVIAO, ASENTO) VALUES (NEXTVAL('SEQ_ASSENTOS'), 1, 'C1');
INSERT INTO ASSENTOS (ID_ASSENTO, ID_AVIAO, ASENTO) VALUES (NEXTVAL('SEQ_ASSENTOS'), 1, 'C2');

INSERT INTO ASSENTOS (ID_ASSENTO, ID_AVIAO, ASENTO) VALUES (NEXTVAL('SEQ_ASSENTOS'), 2, 'A1');
INSERT INTO ASSENTOS (ID_ASSENTO, ID_AVIAO, ASENTO) VALUES (NEXTVAL('SEQ_ASSENTOS'), 2, 'A2');
INSERT INTO ASSENTOS (ID_ASSENTO, ID_AVIAO, ASENTO) VALUES (NEXTVAL('SEQ_ASSENTOS'), 2, 'B1');
INSERT INTO ASSENTOS (ID_ASSENTO, ID_AVIAO, ASENTO) VALUES (NEXTVAL('SEQ_ASSENTOS'), 2, 'B2');
INSERT INTO ASSENTOS (ID_ASSENTO, ID_AVIAO, ASENTO) VALUES (NEXTVAL('SEQ_ASSENTOS'), 2, 'C1');
INSERT INTO ASSENTOS (ID_ASSENTO, ID_AVIAO, ASENTO) VALUES (NEXTVAL('SEQ_ASSENTOS'), 2, 'C2');

INSERT INTO ASSENTOS (ID_ASSENTO, ID_AVIAO, ASENTO) VALUES (NEXTVAL('SEQ_ASSENTOS'), 3, 'A1');
INSERT INTO ASSENTOS (ID_ASSENTO, ID_AVIAO, ASENTO) VALUES (NEXTVAL('SEQ_ASSENTOS'), 3, 'A2');
INSERT INTO ASSENTOS (ID_ASSENTO, ID_AVIAO, ASENTO) VALUES (NEXTVAL('SEQ_ASSENTOS'), 3, 'B1');
INSERT INTO ASSENTOS (ID_ASSENTO, ID_AVIAO, ASENTO) VALUES (NEXTVAL('SEQ_ASSENTOS'), 3, 'B2');
INSERT INTO ASSENTOS (ID_ASSENTO, ID_AVIAO, ASENTO) VALUES (NEXTVAL('SEQ_ASSENTOS'), 3, 'C1');
INSERT INTO ASSENTOS (ID_ASSENTO, ID_AVIAO, ASENTO) VALUES (NEXTVAL('SEQ_ASSENTOS'), 3, 'C2');

-- INSERT VOO
INSERT INTO VOO (ID_VOO, ID_AVIAO, ORIGEM, DESTINO, DATA_VOO, HORA_VOO) VALUES (NEXTVAL('SEQ_VOO'), 1, 'São Paulo', 'Rio de Janeiro', '2019-01-01', '10:00:00');
INSERT INTO VOO (ID_VOO, ID_AVIAO, ORIGEM, DESTINO, DATA_VOO, HORA_VOO) VALUES (NEXTVAL('SEQ_VOO'), 1, 'São Paulo', 'Rio de Janeiro', '2019-01-01', '12:00:00');


INSERT INTO VOO (ID_VOO, ID_AVIAO, ORIGEM, DESTINO, DATA_VOO, HORA_VOO) VALUES (NEXTVAL('SEQ_VOO'), 2, 'São Paulo', 'Rio de Janeiro', '2019-01-01', '10:00:00');
INSERT INTO VOO (ID_VOO, ID_AVIAO, ORIGEM, DESTINO, DATA_VOO, HORA_VOO) VALUES (NEXTVAL('SEQ_VOO'), 2, 'São Paulo', 'Rio de Janeiro', '2019-01-01', '12:00:00');

-- INSERT PASSAGEIRO
INSERT INTO PASSAGEIRO (ID_PASSAGEIRO, ID_VOO, ID_ASSENTO, NOME, IND_BAGAGEM, CLASSE) VALUES (NEXTVAL('SEQ_PASSAGEIRO'), 1, 1, 'JOÃO', TRUE, 1);
